Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bookshop_CATeam11.Models;

namespace Bookshop_CATeam11.Controllers
{
    
    public class BookController : Controller
    {
        BookShopEntities _db = new BookShopEntities();
        // private readonly string currentUser = getCurrentUser;//System.Web.HttpContext.Current.User.Identity.Name;
        // GET: Book
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.CustList = new BusinessLogic().GetBooks;
            return View();
        }
        [AllowAnonymous]
        public ActionResult Show(int? id)  
        {
            if (id == null)    
            {
                ViewBag.BookList = new BusinessLogic().GetBooks;
                return View("Show");
            }
            else
            {
                Book book = new BusinessLogic().GetBook(id);    //book object in details html comes from here
                if (book == null)
                {
                    ViewBag.Id = id;
                    return View("NotBook");
                }
                else
                {
                    ViewBag.Book = book;
                    return View("BookDetails");
                }
            }
        }
        [Authorize]
        public ActionResult CartItems(int? bookid)
        {
            if (bookid > 0)
            {
                if (User.IsInRole("User"))
                {
                    AddToCart(bookid);
                }
                else
                {
                    TempData["info"] = "no access to shopping cart";
                }
                return RedirectToAction("Index");
            }
            else
            {
                List<CartItemsViewModel> carts = (from c in _db.Carts
                                                  join b in _db.Books on c.BookID equals b.BookID
                                                   join m in _db.Memberships on c.MemberID equals m.MemberID
                                                  where m.MemberID == getCurrentUser
                                                  select new CartItemsViewModel
                                                  {
                                                      CartID = c.CartID,
                                                      MemberID = c.MemberID,
                                                      Title = b.Title,
                                                      Cover = b.Cover,
                                                      Price = b.Price,
                                                      ISBN = b.ISBN,
                                                      Author = b.Author,
                                                      Quantity = c.Quantity,
                                                      BookID = b.BookID
                                                  }).ToList();
                if (carts.Count > 0)
                {
                    //   ViewBag.MemberID = currentUser;
                    return View(carts);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }

        [Authorize]
        public ActionResult removeCart(int cartID) {
            Cart cart = _db.Carts.Where(s => s.CartID == cartID && s.MemberID == getCurrentUser).FirstOrDefault();
            if (cart != null)
            {
                _db.Carts.Remove(cart);
                _db.SaveChanges();
            }
            return RedirectToAction("CartItems");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Checkout(List<CartItemsViewModel> viewModel) {
            try
            {
                //List<Sales_Trans> trans = new List<Sales_Trans>();
                //List<Sales_Details> detail = new List<Sales_Details>();
                Promotion pd = _db.Promotions.AsEnumerable().Where(s => s.Start_Time.Date <= DateTime.Now.Date && DateTime.Now.Date <= s.End_Time.Date).FirstOrDefault();

                foreach (CartItemsViewModel item in viewModel)
                {
                    decimal? discountAmt = item.Quantity * item.Price;
                    if (pd != null)
                    {
                        discountAmt = ((100 - pd.Discount_Price) / 100) * discountAmt; 
                    }
                    _db.Sales_Trans.Add(new Sales_Trans {
                        PromotionID = pd != null ? pd.PromotionID : 0,
                        SalesDate = DateTime.UtcNow.Date,
                        Quantity = item.Quantity,
                        Total_Amount = discountAmt,
                        BookID = item.BookID,
                    });
                    Cart cart = _db.Carts.Where(s => s.CartID == item.CartID && s.MemberID == item.MemberID).FirstOrDefault();
                    if (cart != null)
                    {
                        _db.Carts.Remove(cart);
                    }
                }
                _db.SaveChanges();

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Search(SearchViewModel vm)//string searchString, string choice
        {
            string searchString = vm.SearchString, choice = vm.Choice;
            List<Book> books = new List<Book>();
            List<Book> bks = new List<Book>();
            var displayedBooks = new BusinessLogic().GetBooks.Take(5);
            ViewBag.randomBooks = displayedBooks;
            if (choice == "Title")
            {
                books = new BusinessLogic().GetBookByTitle(searchString);
                if (books == null)
                {
                    bks = new BusinessLogic().GetBookByTitle(searchString.Substring(0, 1));
                    //ViewBag.booksRelated = bks;
                    return View("ResultsNotFound", bks);
                }
                else
                {
                    //  ViewBag.booklist = books;
                    return View("ResultsFound", books);
                }
            }
            else if (choice == "ISBN")
            {
                books = new BusinessLogic().GetBookByISBN(searchString);
                if (books == null)
                {
                    bks = new BusinessLogic().GetBookByISBN(searchString.Substring(0, 1));
                    //ViewBag.booksRelated = bks;
                    return View("ResultsNotFound", bks);
                }
                else
                {
                    //   ViewBag.booklist = books;
                    return View("ResultsFound", books);
                }
            }
            else
            {
                books = new BusinessLogic().GetBookByAuthor(searchString);
                if (books == null)
                {
                    bks = new BusinessLogic().GetBookByAuthor(searchString.Substring(0, 1));
                    //ViewBag.booksRelated = bks;
                    return View("ResultsNotFound", bks);
                }
                else
                {
                    //  ViewBag.booklist = books;
                    return View("ResultsFound", books);
                }
            }

        }



        public ActionResult ResultsFound(List<Book> books)
        {

            // ViewBag.booklist = books;
            return View(books);
        }
        public ActionResult ResultsNotFound(List<Book> bks)
        {

            // ViewBag.booklist = books;
            return View(bks);
        }

        public ActionResult Children()
        {
            ViewBag.CustList = new BusinessLogic().GetChildrenBooks;
            return View();
        }
        public ActionResult Nonfict()
        {
            ViewBag.CustList = new BusinessLogic().GetNonfictBooks;
            return View();
        }
        public ActionResult Fin()
        {
            ViewBag.CustList = new BusinessLogic().GetFinBooks;
            return View();
        }
        public ActionResult Tech()
        {
            ViewBag.CustList = new BusinessLogic().GetTechBooks;
            return View();
        }
        public ActionResult EditBookInfo()
        {
            return View(_db.Books.ToList());
        }

        [Authorize(Roles ="Admin,SuperAdmin")]
        public ActionResult Edit(int id = 0)
        {


            Book bookModel = new Book();

            BookShopEntities db = new BookShopEntities();
            var getCategoryList = db.Categories.ToList();
            SelectList list = new SelectList(getCategoryList, "CategoryID", "Name");
            ViewBag.CategoryListName = list;

            if (id != 0)
                bookModel = db.Books.Where(x => x.BookID == id).FirstOrDefault();
            bookModel.CategoryCollection = db.Categories.ToList<Category>();




            return View(bookModel);
        }

        [Authorize(Roles = "Admin,SuperAdmin")]
        [HttpPost]
        public ActionResult Edit(Book bk, HttpPostedFileBase image1)
        {
            //_context.Entry<Bookshop_CATeam11.Models.Book>(bk).State = System.Data.Entity.EntityState.Modified;
            BookShopEntities entities = new BookShopEntities();
            Book updatedBook = (from c in entities.Books
                                where c.BookID == bk.BookID
                                select c).FirstOrDefault();
            var getCategoryList = entities.Categories.ToList();

Controllers/MaintainPromotionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bookshop_CATeam11.Models;

namespace Bookshop_CATeam11.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class MaintainPromotionController : Controller
    {
        BookShopEntities db = new BookShopEntities();
        // GET: MaintainPromotion
        
        public ActionResult Index(string sortOrder)
        {
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "PromotionIDdesc" : "PromotionID";
            ViewBag.DiscountSortParm = sortOrder == "Discount" ? "DiscountDesc" : "Discount";
            ViewBag.StartDateSortParm = sortOrder == "StartDate" ? "StartDateDesc" : "StartDate";
            ViewBag.EndDateSortParm = sortOrder == "EndDate" ? "EndDateAsc" : "EndDate";
            var promotions = from p in db.Promotions
                           select p;
            switch (sortOrder)
            {
                case "PromotionIDdesc":
                    promotions = promotions.OrderByDescending(p => p.PromotionID);
                    break;
                case "Discount":
                    promotions = promotions.OrderBy(p => p.Discount_Price);
                    break;
                case "DiscountDesc":
                    promotions = promotions.OrderByDescending(p => p.Discount_Price);
                    break;
                case "StartDate":
                    promotions = promotions.OrderBy(p => p.Start_Time);
                    break;
                case "StartDateDesc":
                    promotions = promotions.OrderByDescending(p => p.Start_Time);
                    break;
                case "EndDate":
                    promotions = promotions.OrderByDescending(p => p.End_Time);
                    break;
                case "EndDateAsc":
                    promotions = promotions.OrderBy(p => p.End_Time);
                    break;
                default:
                    promotions = promotions.OrderBy(p => p.PromotionID);
                    break;
            }
            return View(promotions.ToList());
        }

        [HttpPost]

        public ActionResult Delete(int id)
        {
            var q = from y in db.Promotions where y.PromotionID == id select y;
            db.Promotions.Remove(q.First());
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            Promotion p = db.Promotions.Single(x => x.PromotionID == id);
            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(Promotion promotion)
        {
            Promotion thisPromo = db.Promotions.Single(x => x.PromotionID == promotion.PromotionID);
            thisPromo.Discount_Price = promotion.Discount_Price;
            thisPromo.Start_Time = promotion.Start_Time;
            thisPromo.End_Time = promotion.End_Time;

            if (ModelState.IsValid)
            {
                db.SaveChanges();
                TempData["Success"] = "Changes Saved!";
            }
            return View(promotion);
        }


        public ActionResult Add()
        {
            Promotion model = new Promotion();
            return View(model);
        }
        
        [HttpPost]

        public ActionResult Add(Promotion p)
        {
            if (ModelState.IsValid)
            {
                db.Promotions.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(p);
            }
        }
        
    }
}

Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using Bookshop_CATeam11.Models;

namespace Bookshop_CATeam11.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }
        // GET: Role
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }
        //create a new role

        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }
        //create new role

        [HttpPost]
        public ActionResult Create (IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/HomeStyleSheet.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Books", "Index", "Book")</li>
                    <li>@Html.ActionLink("Promotions", "Promotion", "Home", null, new { @class = "" })</li>

                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("SuperAdmin"))
                        {
                            <li>@Html.ActionLink("Maintain Roles", "Index", "Role")</li>
                        }
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Maintain Promotion", "Index", "MaintainPromotion", null, new { @class = "" })</li>
                            <li>@Html.ActionLink("Maintain Book", "EditBookInfo", "Book", null, new { @class = "" })</li>

                        }
                        if (User.IsInRole("User"))
                        {
                            <li>@Html.ActionLink("Shopping Cart", "CartItems", "Book", null, new { @id = "cart-count", @class = "" })</li>
                        }
                    }
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Event", "Events", "Home", null, new { @class = "" })</li>
                    <li>@Html.ActionLink("Stores", "OurStores", "Home", null, new { @class = "" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <span style="font-size: 84px; color: dodgerblue;">
                <i class="fab fa-cc-visa" style="font-size:50px"></i>

                <span style="font-size: 84px; color: orangered;">
                    <i class="fab fa-cc-mastercard" style="font-size:50px"></i>

                    <span style="font-size: 84px; color: cornflowerblue;">
                        <i class="fab fa-cc-amex" style="font-size:50px"></i>

                        <span style="font-size: 84px; color: steelblue;">
                            <i class="fab fa-cc-paypal" style="font-size:50px"></i>
                        </span>
                    </span>
                </span>
            </span>
            <p>&copy; @DateTime.Now.Year - Amanda Books</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function(){
            $.ajax({
                url: "@Url.Action("CartCount", "Book")", success: function(result){
                    $("#cart-count").html("(" + result + ") " + "Shopping Cart");
                    }});
        });
    </script>
</body>
</html>